# .travis.yml
# This script pushes a new index to Algolia
language: ruby
addons:
  apt:
    update: true
cache: bundler
script:
  - bundle exec jekyll algolia
branches:
  only:
    - gh-pages
rvm:
 - 2.4
